did_django_template_tags/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls", namespace ="main"))
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = "main"

urlpatterns = [
	
	path('', views.index, name="home"),
	url(r'^filter', views.filter, name="filter"),
	url(r'^bespoke-filter', views.bespoke_filter, name="bespoke-filter"),

	]

main/models.py
from django.db import models

main/views.py
from django.shortcuts import render
from django.utils import timezone


'''
Basic index view
'''
def index(request):

	regroup_list = [
	    {'name': 'John', 'age': '19', 'country': 'UK'},
	    {'name': 'Mark', 'age': '22', 'country': 'USA'},
	    {'name': 'Frank', 'age': '55', 'country': 'France'},
	    {'name': 'Lewis', 'age': '27', 'country': 'USA'},
	    
	    {'name': 'Matt', 'age': '38', 'country': 'Germany'},
	    ]

	#template tag does not sort the dict
	#This is sorting a list of dics by key["family"]
	reset_cycle_list = sorted([

	    {'name': 'Jojen Reed', 'family': 'Reed'},
	    {'name': 'Daenerys Targaryen', 'family': 'Targaryen'},
	    {'name': 'Sansa Stark', 'family': 'Stark'},
	    {'name': 'Joffrey Baratheon', 'family': 'Lannister'},
	    {'name': 'Eddard Stark', 'family': 'Stark'},
	    {'name': 'Tyrion Lannister', 'family': 'Lannister'},
	    {'name': 'Arya Stark', 'family': 'Stark'},
	    {'name': 'Stannis Baratheon', 'family': 'Baratheon'},
    ], key=lambda k: k['family'])

    
	# reset_cycle_list = sorted(reset_cycle_list, key=lambda k: k['family'])
	
	context = {
		"cycle_list": ["This", "Is", "Cycle", "example"],
		"firstof_1": False,
		"firstof_2": False,
		"firstof_3": "This will be displayed",
		"for_list": ["123 Winterfell,", "Kings Road", "The North", "PO BOX - 5N0W"],
		"for_dict": {
			"first_line": "123 Winterfell,",
			"second_line": "Kings Road,",
			"town": "The North,",
			"postcode": "PO BOX - 5N0W"},
		"if_list": [],
		"regroup_list": regroup_list,
		"reset_cycle_list": reset_cycle_list,
	}
	return render(request, 'main/index.html', context)



'''
Basic filter view 
'''
def filter(request):

	dictsort = [
	    {'name': 'John', 'age': '19', 'country': 'UK'},
	    {'name': 'Mark', 'age': '22', 'country': 'USA'},
	    {'name': 'Frank', 'age': '55', 'country': 'France'},
	    {'name': 'Lewis', 'age': '27', 'country': 'USA'},
	    {'name': 'Matt', 'age': '38', 'country': 'Germany'},
	    ]

	context = {
		"add": 3,
		"addslashes": "I'm building a demo",
		"capfirst": "winterfell",
		"center": "Kings Landing",
		"cut": "Kings Landing",
		"date": timezone.now(),
		"default": "",
		"default_if_none": None,
		"dictsort": dictsort,
		"dictsortreversed": dictsort,
		"divisibleby": 21,
		"filesizeformat": 123456789,
		"first": ["This", "Is", "First"],
		"floatformat": 39.4564765,
		"get_digit": 132456789,
		"join": ["This", "Is", "First"],
		"last": ["This", "Is", "Last"],
		"length": ["This", "Is", "First"],
		"length_is": ["This", "Is", "First"],
		"lower": "HELLO",
		"apnumber":32156,
		"intcomma":987654321,
		"naturalday": timezone.now()	
	}
	return render(request, 'main/filter.html', context)



'''
Basic filter view 
'''
def bespoke_filter(request):

	context = {
		"price1": 2,
		"price2": 23.4567687,
		"price3": 24.1,		
	}
	return render(request, 'main/bespoke_filter.html', context)

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- visit https://fonts.google.com/specimen/Courier+Prime?preview.text_type=custom to get script-->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'main.css' %}"></link>

  <!-- This allows us to extend the head scripts in HTML docs that have special requirements-->
  {% block extend_head %}

  {% endblock %}

</head>
<body>

  <!-- This allows us to extend the nav bar in HTML docs that have special requirements-->
  {% block extend_nav %}

  {% endblock %}

  <div class="div-container">
    
    {% include 'main/partials/logo.html' %}

    {% block content %}

    {% endblock %}

  </div>

  <!--visit https://code.jquery.com/ for jquery script-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

  <!-- This allows us to extend the foot scripts in HTML docs that have special requirements-->
  {% block extend_footer %}

  {% endblock %}

  <script src="{% static 'main.js' %}"></script>
  

</body>
</html>

main/templates/main/bespoke_filter.html
{% extends 'main/base.html' %}
{% load static %}
{% load did_tags %}


{% block extend_head %}

{% endblock %}

{% block extend_nav %} 

<ul class="sidenav">
  <li><a href="{% url 'main:home' %}">Demo Django Template Tags</a></li>
  <li><a href="{% url 'main:filter' %}">Demo Django Template Filters</a></li>
  <li><a class="active" href="{% url 'main:bespoke-filter' %}">Demo Django Bespoke Template Filters</a></li>
</ul>

{% endblock %}

{% block content %}

<h3>Django Bespoke Template Tag Demo - Home</h3>

<div class="container">

	<table>
	    <thead>
	      <tr>
	        <th>Field</th>
	        <th>Before Filter</th>
	        <th>After Filter</th>
	      </tr>
	    </thead>
	    <tbody>
	    	
		    <tr>
		    	<td>Price 1</td>
		    	<td>{{price1}}</td>
		    	<td>{{price1|price}}</td>
		    </tr>
			<tr>
		    	<td>Price 2</td>
		    	<td>{{price2}}</td>
		    	<td>{{price2|price}}</td>
		    </tr>

		    <tr>
		    	<td>Price 3</td>
		    	<td>{{price3}}</td>
		    	<td>{{price3|price}}</td>
		    </tr>

		</tbody>
	</table>

</div>

{% endblock %}

{% block extend_footer %}


<script type="text/javascript">

</script>


{% endblock %}

main/templates/main/filter.html
{% extends 'main/base.html' %}
{% load static %}
{% load humanize %}


{% block extend_head %}

{% endblock %}

{% block extend_nav %} 

<ul class="sidenav">
  <li><a href="{% url 'main:home' %}">Demo Django Template Tags</a></li>
  <li><a class="active" href="{% url 'main:filter' %}">Demo Django Template Filters</a></li>
  <li><a href="{% url 'main:bespoke-filter' %}">Demo Django Bespoke Template Filters</a></li>
</ul>

{% endblock %}

{% block content %}

<h3>Django Template Tag Demo - Home</h3>

<div class="container">

	<table>
	    <thead>
	      <tr>
	        <th>Field</th>
	        <th>Before Filter</th>
	        <th>After Filter</th>
	      </tr>
	    </thead>
	    <tbody>
	    	
		    <tr>
		    	<td>Add</td>
		    	<td>{{add}}</td>
		    	<td>{{add|add:2}}</td>
		    </tr>

		    <tr>
		    	<td>Addslashes</td>
		    	<td>{{addslashes}}</td>
		    	<td>{{addslashes|addslashes}}</td>
		    </tr>

		    <tr>
		    	<td>Capfirst</td>
		    	<td>{{capfirst}}</td>
		    	<td>{{capfirst|capfirst}}</td>
		    </tr>

		    <tr>
		    	<td>Center</td>
		    	<td>{{center}}</td>
		    	<td>{{center|center:40}}</td>
		    </tr>

		    <tr>
		    	<td>Cut</td>
		    	<td>{{cut}}</td>
		    	<td>{{cut|cut:" "}}</td>
		    </tr>

		    <tr>
		    	<td>Date</td>
		    	<td>{{date}}</td>
		    	<td>{{date|date:"D d M Y"}}</td>
		    </tr>

		    <tr>
		    	<td>Default</td>
		    	<td>{{default}}</td>
		    	<td>{{default|default:"Nowt"}}</td>
		    </tr>

		    <tr>
		    	<td>Default</td>
		    	<td>{{default_if_none}}</td>
		    	<td>{{default_if_none|default_if_none:"Still nowt"}}</td>
		    </tr>

		    <tr>
		    	<td>Dictsort</td>
		    	<td>{{dictsort}}</td>
		    	<td>{{dictsort|dictsort:"age"}}</td>
		    </tr>
		    <tr>
		    	<td>Dictsortreversed</td>
		    	<td>{{dictsortreversed}}</td>
		    	<td>{{dictsortreversed|dictsortreversed:"age"}}</td>
		    </tr>

		    <tr>
		    	<td>Divisibleby</td>
		    	<td>{{divisibleby}}</td>
		    	<td>{{divisibleby|divisibleby:"7"}}</td>
		    </tr>

		    <tr>
		    	<td>Filesizeformat</td>
		    	<td>{{filesizeformat}}</td>
		    	<td>{{filesizeformat|filesizeformat}}</td>
		    </tr>

		    <tr>
		    	<td>First</td>
		    	<td>{{first}}</td>
		    	<td>{{first|first}}</td>
		    </tr>

		    <tr>
		    	<td>Floatformat</td>
		    	<td>{{floatformat}}</td>
		    	<td>{{floatformat|floatformat}}</td>
		    </tr>

		    <tr>
		    	<td>Get_digit</td>
		    	<td>{{get_digit}}</td>
		    	<td>{{get_digit|get_digit:"2"}}</td>
		    </tr>

		    <tr>
		    	<td>Floatformat</td>
		    	<td>{{floatformat}}</td>
		    	<td>{{floatformat|floatformat}}</td>
		    </tr>

		    <tr>
		    	<td>Join</td>
		    	<td>{{join}}</td>
		    	<td>{{join|join:"-"}}</td>
		    </tr>

		    <tr>
		    	<td>Last</td>
		    	<td>{{last}}</td>
		    	<td>{{last|last}}</td>
		    </tr>

		    <tr>
		    	<td>Length</td>
		    	<td>{{length}}</td>
		    	<td>{{length|length}}</td>
		    </tr>

		    <tr>
		    	<td>Length_is</td>
		    	<td>{{length_is}}</td>
		    	<td>{{length|length_is:"3"}}</td>
		    </tr>

		    <tr>
		    	<td>Lower</td>
		    	<td>{{lower}}</td>
		    	<td>{{lower|lower}}</td>
		    </tr>

		    <tr>
		    	<td>Apnumber (Humanize)</td>
		    	<td>{{apnumber}}</td>
		    	<td>{{apnumber|apnumber}}</td>
		    </tr>

		    <tr>
		    	<td>Intcomma (Humanize)</td>
		    	<td>{{intcomma}}</td>
		    	<td>{{intcomma|intcomma}}</td>
		    </tr>

		    <tr>
		    	<td>Naturalday (Humanize)</td>
		    	<td>{{naturalday}}</td>
		    	<td>{{naturalday|naturalday}}</td>
		    </tr>


		</tbody>
	</table>

</div>

{% endblock %}

{% block extend_footer %}


<script type="text/javascript">

</script>


{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}

{% block extend_nav %} 

<ul class="sidenav">
  <li><a class="active" href="{% url 'main:home' %}">Demo Django Template Tags</a></li>
  <li><a href="{% url 'main:filter' %}">Demo Django Template Filters</a></li>
  <li><a href="{% url 'main:bespoke-filter' %}">Demo Django Bespoke Template Filters</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Django Template Tag Demo - Home</h3>

<div class="container">


	{% comment "Optional note" %}
    <p>Commented out text with {{ create_date|date:"c" }}</p>
	{% endcomment %}

	<h4>Tag - Cycle</h4>
	<table>
	    <thead>
	      <tr>
	        <th>Field</th>
	        <th>Data</th>
	      </tr>
	    </thead>
	    <tbody>
			{% for c in cycle_list %}
		    <tr>
		    	<td>{% cycle 'row1' 'row2' %}</td>
		    	<td>{{c}}</td>
		    </tr>
			{% endfor %}
		</tbody>
	</table>

	<br>

	<h4>Tag - Firstof</h4>
    <input type="text" readonly id="id-first-of" value="{% firstof firstof_1 firstof_2 firstof_3 %}">

    <br>

    <h4>Tag - For (with list)</h4>

    {% for f in for_list %}
    	<address>{{f}} </address>
    {% endfor %}

    <h4>Tag - For (with dict)</h4>

    {% for key, value in for_dict.items %}
    	<address>{{key}}: {{value}} </address>
    {% endfor %}

    <h4>Tag - If</h4>

    {% if if_list %}
    	{% for i in if_list %}
	    <input type="text" readonly value="{{i}}">
	    {% endfor %}
    {% else %}

    <input type="text" readonly value="This is displayed">

    {% endif %}

    <h4>Tag - Input</h4>
    {% include 'main/partials/input.html' %}

    <h4>Tag - Lorem (1 x paragraph)</h4>

    {% lorem 1 p %}

    <h4>Tag - Now</h4>

    <p>All rights reserved, &copy{% now "Y" %} <a href="javascript:void(0)">Didcoding</a></p>

    <h4>Tag - Regroup</h4>

    {% regroup regroup_list by country as country_list %}

    <ul>
	{% for country in country_list %}
	    <li>{{ country.grouper }}
		    <ul>
		        {% for n in country.list %}
		          <li>{{ n.name }}: {{ n.age }}</li>
		        {% endfor %}
		    </ul>
	    </li>
	{% endfor %}
	</ul>

	<h4>Tag - Reset Cycle</h4>

	{% regroup reset_cycle_list by family as family_list %}

	{% for family in family_list %}
		<li>{{ family.grouper }}
			<ul>
		        {% for n in family.list %}
		          <li>{{ n.name }}: {% cycle 'Dead' 'Alive' %}</li>
		        {% endfor %}
		        {% resetcycle %}
		    </ul>
	    </li>
	{% endfor %}

	<h4>Tag - With (and filter)</h4>
	{% with families=family_list.grouper.count %}
	<input type="text" readonly id="id-first-of" value="{{family_list|length}} Westeros families">
	{% endwith %}
	

</div>

{% endblock %}

{% block extend_footer %}


<script type="text/javascript">

</script>


{% endblock %}

main/templates/main/partials/input.html
<input type="text" readonly id="id-include" value="This is an include input">

main/templates/main/partials/logo.html
{% load static %}
<a href="{% url 'main:home' %}">
	<div class="brand-logo">
		<img class="logo" src="{% static 'branding/did_logo.gif' %}" />
	</div>
</a>